compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAuthToken: "${NPM_AUTH_TOKEN:-}"

npmPublishAccess: public

npmPublishRegistry: "${NPM_REGISTRY:-}"

yarnPath: .yarn/releases/yarn-4.5.0.cjs
